# Dockerfile.backend

# Base image
FROM node:18-alpine AS base

# Set working directory
WORKDIR /usr/src/app

# Install dependencies
COPY backend/package*.json ./
RUN npm install --only=production

# Copy prisma schema
COPY backend/prisma ./prisma/

# Generate prisma client
RUN npx prisma generate

# Copy app source
COPY backend/dist ./dist

# Expose port
EXPOSE 3000

# Start command
CMD ["node", "dist/main"]